Disable the custom installation

diff --git a/script/extract-secrets b/script/extract-secrets
--- a/script/extract-secrets
+++ b/script/extract-secrets
@@ -5,27 +5,39 @@
 set -e
 cd "$(git rev-parse --show-toplevel)"
 
-if [ -z "$OP_SESSION_my" ]; then
-  echo "==> Logging into 1Password…"
-  eval "$(op signin my.1password.com jamie@jamieconnolly.com)"
-fi
+# if [ -z "$OP_SESSION_my" ]; then
+  # echo "==> Logging into 1Password…"
+  # eval "$(op signin my.1password.com jamie@jamieconnolly.com)"
+# fi
 
-echo "==> Setting up GPG…"
-if ! command -v gpg >/dev/null 2>&1; then
-  echo "!!! Error: GPG is not installed" >&2
-  exit 1
-fi
+# echo "==> Setting up GPG…"
+# if ! command -v gpg >/dev/null 2>&1; then
+  # echo "!!! Error: GPG is not installed" >&2
+  # exit 1
+# fi
 
-mkdir ~/.gnupg
-chmod 700 ~/.gnupg
+# mkdir ~/.gnupg
+# chmod 700 ~/.gnupg
 
-op get document 'GPG - Owner Trust' > ~/.gnupg/jamie@jamieconnolly.com.ownertrust.gpg-txt
-op get document 'GPG - Public Key' > ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key
-op get document 'GPG - Secret Subkeys' > ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key
+# op get document 'GPG - Owner Trust' > ~/.gnupg/jamie@jamieconnolly.com.ownertrust.gpg-txt
+# op get document 'GPG - Public Key' > ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key
+# op get document 'GPG - Secret Subkeys' > ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key
 
-gpg --import ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key
-gpg --import-ownertrust < ~/.gnupg/jamie@jamieconnolly.com.ownertrust.gpg-txt
+# gpg --import ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key
+# gpg --import-ownertrust < ~/.gnupg/jamie@jamieconnolly.com.ownertrust.gpg-txt
 
-rm ~/.gnupg/jamie@jamieconnolly.com.ownertrust.gpg-txt
-rm ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key
-rm ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key
+# rm ~/.gnupg/jamie@jamieconnolly.com.ownertrust.gpg-txt
+# rm ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key
+# rm ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key
+
+# echo "==> Storing SSH keys in keychain…"
+# if ! command -v ssh >/dev/null 2>&1; then
+  # echo "!!! Error: SSH is not installed" >&2
+  # exit 1
+# fi
+
+# op get document 'SSH - Private Key' > ~/.ssh/id_ed25519
+# ssh-add -K ~/.ssh/id_ed25519
+
+# maybe use this
+# ssh-add --apple-use-keychain
